CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, nickname TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS documents (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id), title TEXT NOT NULL, source_type TEXT NOT NULL, status TEXT NOT NULL, word_count INT DEFAULT 0, deleted_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS document_files (id BIGSERIAL PRIMARY KEY, document_id BIGINT REFERENCES documents(id), file_type TEXT NOT NULL, original_filename TEXT, object_key TEXT NOT NULL, content_type TEXT, file_size BIGINT, etag TEXT, upload_status TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS words (id BIGSERIAL PRIMARY KEY, word TEXT NOT NULL, word_lower TEXT UNIQUE NOT NULL, lemma TEXT, phonetic TEXT, part_of_speech TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS word_occurrences (id BIGSERIAL PRIMARY KEY, word_id BIGINT REFERENCES words(id), document_id BIGINT REFERENCES documents(id), paragraph_index INT, sentence TEXT, context TEXT, position INT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS embeddings (id BIGSERIAL PRIMARY KEY, document_id BIGINT REFERENCES documents(id), word_id BIGINT REFERENCES words(id), content_type TEXT, content TEXT, embedding vector(384), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS error_records (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id), document_id BIGINT REFERENCES documents(id), word_id BIGINT REFERENCES words(id), error_type TEXT, user_answer TEXT, correct_answer TEXT, source_task_id BIGINT, created_at TIMESTAMPTZ DEFAULT now(), resolved_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS tasks (id BIGSERIAL PRIMARY KEY, task_type TEXT NOT NULL, business_id BIGINT, user_id BIGINT REFERENCES users(id), status TEXT NOT NULL, progress INT DEFAULT 0, result JSONB, error_message TEXT, created_at TIMESTAMPTZ DEFAULT now(), started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ);
